### ISSUE TITLE
Error in firebase.login: TypeError: Cannot read property 'FirebaseAuth' of undefined

### ISSUE THREAD

**Issue by LuisSarmientoM** [EddyVerbruggen/nativescript-plugin-firebase#1431]
I'm trying to log in with email and password with angular, when I call the service to log in, I get the following error:

![image](https://user-images.githubusercontent.com/42702720/66940755-21917c80-f00b-11e9-9fcc-f7f1d7a21308.png)

This is my firebase.nativescript:
{
    "external_push_client_only": false,
    "using_ios": true,
    "using_android": true,
    "analytics": false,
    "firestore": true,
    "realtimedb": false,
    "authentication": true,
    "remote_config": false,
    "performance_monitoring": false,
    "messaging": false,
    "in_app_messaging": false,
    "crashlytics": false,
    "storage": false,
    "functions": false,
    "facebook_auth": false,
    "google_auth": false,
    "admob": false,
    "dynamic_links": false,
    "ml_kit": false
}

And i used plugin version 10.0.2

**Comment by EddyVerbruggen** [comment]
Did you just update to the latest version? If so, remove node_modules and platforms please. Otherwise share the bit from ‘adb logcat’ with this error.

**Comment by LuisSarmientoM** [comment]
no, remove **node_modules** and the **platforms** folder, reinstall with **npm install,** this didn't work.
I started a project from 0, I followed the Authentication documentation and I get the same error.

i used the next code
**Auth Service**
![image](https://user-images.githubusercontent.com/42702720/66955574-43e5c300-f028-11e9-8ce8-79a2a0e8525a.png)

**app.component.ts** // main Component of the project
![image](https://user-images.githubusercontent.com/42702720/66955666-74c5f800-f028-11e9-95f9-7df6e349f380.png)

**This is the login component**
![image](https://user-images.githubusercontent.com/42702720/66955847-d8e8bc00-f028-11e9-9b55-01bafc637fe3.png)

I'm using lazyloading, and then I'll implement AuthGuard.

**Comment by LuisSarmientoM** [comment]
This is the mistake I have now.

I know that Firebase already initialized, is solved by moving firebase.init to the main.ts

`firebase.init error: Firebase already initialized
LOG from device P20 Luis Sarmiento : Error in firebase.login: TypeError: Cannot read property 'FirebaseAuth' of undefined
LOG from device P20 Luis Sarmiento : ERROR Error: Uncaught (in promise): Object: {"code":"auth/exception","message":"TypeError: Cannot read property 'FirebaseAuth' of undefined"`

**Comment by JohanBeumer** [comment]
Hi,

I ceated a PR that solves this issue.
@LuisSarmientoM as a workaround you can enable analytics in the json.
However I don't know if that gives any negative side effect.

**Comment by gambheera** [comment]
Seems like still having this issue. @JohanBeumer unfortunately  enabling analytics in the json doesn't work for me. :(

**Comment by wowatarasov** [comment]
Does anyone have a solution?

**Comment by manojdcoder** [comment]
@wowatarasov Which version of plugin you are using? I have tested it on latest (v10.5.0), it works on both iOS & Android. Try running a clean build.

**Comment by kikushi** [comment]
Seems like still having this issue @EddyVerbruggen and  enabling analytics in the json doesn't work for me
