### ISSUE TITLE
Received status code 502 from server: Bad Gateway

### ISSUE THREAD

**Issue by kriefsacha** [EddyVerbruggen/nativescript-plugin-firebase#1860]
Hi,

I'm trying to build my app but i have an error:

> Build file 'C:\Users\....\OneDrive\Documents\Projets\GitHub\....\platforms\android\app\build.gradle' line: 598
> A problem occurred configuring project ':app'.
> Could not GET 'https://dl.bintray.com/triniwiz/maven/com/google/firebase/firebase-ml-common/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

Im on nativescript angular 6.3.3.

Package.json:

```
{
  "nativescript": {
    "id": "org.nativescript.....",
    "tns-ios": {
      "version": "6.5.2"
    },
    "tns-android": {
      "version": "6.5.3"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/geolocation": "^8.0.1",
    "@nativescript/theme": "^3.0.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@nstudio/nativescript-camera-plus": "^3.1.1",
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "@nstudio/nativescript-pulltorefresh": "^2.0.0",
    "@nstudio/nativescript-snackbar": "^1.1.2",
    "nativescript-angular": "^8.20.4",
    "nativescript-background-http": "^4.2.1",
    "nativescript-camera": "^4.4.0",
    "nativescript-datetimepicker": "^1.2.3",
    "nativescript-imagecropper": "^3.0.0",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-nfc": "4.0.1",
    "nativescript-permissions": "^1.3.8",
    "nativescript-plugin-firebase": "9.0.2",
    "nativescript-sound-kak": "^1.2.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-chart": "^7.1.1",
    "nativescript-ui-sidedrawer": "^8.0.1",
    "nativescript-webview-interface": "^1.4.2",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^6.4.0",
    "tns-core-modules": "^6.3.2",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "~0.5.0",
    "@ngtools/webpack": "~8.2.0",
    "@types/jasmine": "^3.5.11",
    "nativescript-dev-webpack": "^1.4.1",
    "tns-platform-declarations": "6.0.1",
    "typescript": "~3.5.3"
  },
  "readme": "NativeScript Application"
}

```

Thank you

**Comment by paul-castro** [comment]
Hi @kriefsacha, any update on this?

**Comment by kriefsacha** [comment]
@paul-castro from what i remember it just resolved by himself..

**Comment by paul-castro** [comment]
@kriefsacha I updated all my plugins, but sadly I still encountering issue on bintray. Still getting error 502
