### ISSUE TITLE
Upload failed. com.google.firebase.storage.StorageException

### ISSUE THREAD

**Issue by lukeramsden** [EddyVerbruggen/nativescript-plugin-firebase#277]
I'm getting this error:
`Upload failed. com.google.firebase.storage.StorageException: An unknown error occurred, please check the HTTP result code and inner exception for server response.`

I'm using NativeScript-Camera to take a photo, save it to a file, and then upload it. It works fine on iOS, but doesn't work on Android.
Here's my code (in TypeScript):
```
import * as fs from 'file-system'
import * as frame from 'ui/frame'
import * as utils from 'utils/utils'
import * as observableModule from 'data/observable'
import * as imageSource from "image-source"
import * as camera from 'nativescript-camera'
import * as image from 'ui/image'
import {
  GestureTypes
} from 'ui/gestures'
import {
  ImageFormat
} from 'ui/enums'
import * as view from "ui/core/view";
import * as firebase from 'nativescript-plugin-firebase'
const dialog = require('nativescript-dialog')
const pd = new observableModule.Observable()

var imageContainer
var imageTaken = false
var fileLocation

exports.loaded = args => {
  let page = args.object
  imageContainer = view.getViewById(page, "img")
  let textField = page.getViewById("textField")
  let observer = page.observe(GestureTypes.tap, function (args) {
    textField.dismissSoftInput()
  })
  pd.set('imageTaken', typeof imageContainer.imageSource === "undefined" ? false : imageTaken)
  pd.set('loading', false)
  pd.set('completeness', 0)
  page.bindingContext = pd
}

exports.takePhoto = args => {
  camera.requestPermissions()
  const options = {
    width: 600,
    height: 600,
    keepAspectRatio: true,
    saveToGallery: false
  }
  camera.takePicture(options)
    .then(imageAsset => {
      imageSource.fromAsset(imageAsset).then(res => {
        //save the source image to a file, then send that file path to firebase
        console.log('Taken Picture')
        pd.set('loading', true)
        imageContainer.imageSource = res
        let imgsrc = res
        fileLocation = fs.knownFolders.documents().path + '/img-' + Date.now() + '.png'
        imgsrc.saveToFile(fileLocation, ImageFormat.png)
        console.log('Picture saved as file: ' + fileLocation)
        imageTaken = true
        pd.set('loading', false)
        pd.set('imageTaken', true)
      })
    }).catch(err => {
      imageTaken = false
      pd.set('imageTaken', false)
      console.log("Error -> " + err.message)
    })
}

exports.sendPhoto = args => {
  console.log(imageTaken)
  console.log(fileLocation)
  let imageName = Date.now() + (Math.random() * 10)
  if (imageTaken && typeof imageContainer.imageSource !== "undefined") {
    firebase.uploadFile({
      remoteFullPath: 'img-' + imageName + '.png',
      localFullPath: fileLocation,
      onProgress: status => {
        console.log("Uploaded fraction: " + status.fractionCompleted)
        console.log("Percentage complete: " + status.percentageCompleted)
        pd.set('loading', true)
        pd.set('completeness', status.percentageCompleted)
      }
    }).then(
      uploadedFile => {
        console.log("File uploaded: " + JSON.stringify(uploadedFile))
        pd.set('loading', false)
        dialog.show({
          title: "Success",
          message: "Image uploaded!",
          okButtonText: "Close"
        })
      },
      error => {
        console.log("File upload error: " + error)
        pd.set('loading', false)
        dialog.show({
          title: "Error",
          message: error,
          okButtonText: "OK"
        })
      })
  } else {
    dialog.show({
      title: "Error",
      message: "Please take a photo first.",
      okButtonText: "OK"
    })
  }
}
```

Can you shed any light on the issue @EddyVerbruggen?

**Comment by EddyVerbruggen** [comment]
What does `adb logcat` tell you?

**Comment by lukeramsden** [comment]
@EddyVerbruggen I put it in a pastebin: http://pastebin.com/F3aUC9Hm

**Comment by EddyVerbruggen** [comment]
Could it be an authentication issue as [mentioned here](http://webcache.googleusercontent.com/search?q=cache:_LUP4uceNGkJ:stackoverflow.com/questions/38384618/firebase-storage-upload-error-firstorageerrordomain-code-13000+&cd=3&hl=nl&ct=clnk&gl=nl)?

**Comment by lukeramsden** [comment]
This is my rules though:
```
service firebase.storage {
  match /b/<redacted>{
    match /{allPaths=**} {
    	allow write: if request.resource.size < 20 * 1024 * 1024;
      allow read: if request.auth != null;
    }
  }
}
```
So it shouldn't need authentication, and it works fine on iOS without it.

**Comment by EddyVerbruggen** [comment]
Perhaps we need to rule out a problem with the image. Can you try and see what happens when uploading a file from the app folder? Much like [this](https://github.com/EddyVerbruggen/nativescript-plugin-firebase-demo/blob/e3867a7855fe9bdf9cf0f3714e513ca5c99e0692/Firebase/app/main-view-model.js#L719)?

**Comment by lukeramsden** [comment]
After changing my code to:
```
    var appPath = fs.knownFolders.currentApp().path;
    var logoPath = appPath + "/res/telerik-logo.png";
    firebase.uploadFile({
      remoteFullPath: 'uploads/images/telerik-logo-uploaded.png',
      localFile: fs.File.fromPath(logoPath),
      onProgress: status => {
        console.log("Uploaded fraction: " + status.fractionCompleted)
        console.log("Percentage complete: " + status.percentageCompleted)
        pd.set('loading', true)
        pd.set('completeness', status.percentageCompleted)
      }
```
It still doesn't work.

**Comment by lukeramsden** [comment]
I'm getting this error through logcat, which I wasn't getting before:
```
02-07 13:41:58.705  3888  4037 W GooglePlayServicesUtil: Google Play services out of date.  Requires 10084000 but found 9879480
02-07 13:41:58.705  3888  4037 W DynamiteModule: Local module descriptor class for com.google.android.gms.firebasestorage not found.
02-07 13:41:58.705  3888  4037 I DynamiteModule: Considering local module com.google.android.gms.firebasestorage:0 and remote module com.google.android.gms.firebasestorage:0
02-07 13:41:58.706  3888  4037 E NetworkRqFactoryProxy: NetworkRequestFactoryProxy failed with a RemoteException:
02-07 13:41:58.706  3888  4037 E NetworkRqFactoryProxy: com.google.android.gms.dynamite.DynamiteModule$zza: No acceptable module found. Local version is 0 and remote version is 0
```

**Comment by EddyVerbruggen** [comment]
Have you tried updating play services? (run `android` from a terminal and scroll to the bottom)

**Comment by lukeramsden** [comment]
![image](https://cloud.githubusercontent.com/assets/13789719/22693716/52e76242-ed3c-11e6-8f9c-d84504b8fdd8.png)
All up to date

**Comment by lukeramsden** [comment]
@EddyVerbruggen Do you think it's a problem with the emulator? I don't have an Android phone to test with ATM, but I know someone I think I can borrow off.

**Comment by EddyVerbruggen** [comment]
I guess that error message may be related to the play services version on the emulator rather than your build. Makes sense as it crashes at runtime.. good idea to try a real device!

**Comment by lukeramsden** [comment]
@EddyVerbruggen After buying a shit second hand Android phone, and a massive amount of headache getting the app to build, I've got it working. Turns out, it was the emulator. Maybe put in the storage docs saying if you get the error i was getting, that its probably the emulator and to try it on a real device.

**Comment by EddyVerbruggen** [comment]
Thanks for reporting that back and sorry for your headache. I hope folks will find this issue as well when searching for a similar error.

**Comment by lukeramsden** [comment]
@EddyVerbruggen [I made a Gist of what I had to do](https://gist.github.com/lukeramsden/e49b377004226b3073b8bcd6190d2746), is there a way to automate this?

**Comment by lukeramsden** [comment]
@EddyVerbruggen I've figured out the problem. When you run `tns install`, its not running the `npm run setup` script, because running that fixes the problem. It install the `after-prepare` hooks for firebase, which stops me from having to do this manually. Maybe put on the homepage that every time you run `tns install` to run `npm run setup`?

**Comment by EddyVerbruggen** [comment]
Just curious: why do you ever run `tns install`?

Note that this used to not be a problem, but {N} 2.5.0 broke the postinstall script so it's not started automatically anymore when installing the plugin. Manual invoking the setup script is required (and that's in the readme).. but I hope that {N} issue gets fixed soon.

**Comment by lukeramsden** [comment]
Ahhh I didn't know that, I started the app on 2.4.0 and it worked. I use `tns install` because I switch between computers a lot, and because I use git-flow, after spending a full week on one machine my git history is so different I need to re-clone sometimes.

**Comment by EddyVerbruggen** [comment]
Ah, yes I understand. The good news is the {N} issue I mentioned has been fixed and it will be released soon. And I can also look into how parts of the postinstall script can still run even with todays {N} version. Let me ponder a bit..

**Comment by najimali** [comment]
I am running it on real device but still getting error same error --"An unknown error occurred, please check the HTTP result code and inner exception for server response."

**Comment by najimali** [comment]
Please how to solve this

**Comment by ToBemBrabo** [comment]
implementation 'com.google.firebase:firebase-storage:17.0.0'

This worked for me.
