### ISSUE TITLE
[iOS] Background notifications

### ISSUE THREAD

**Issue by mfradcourt** [EddyVerbruggen/nativescript-plugin-firebase#382]
I'm facing a problem to setup the background notifications on a real iphone device (iphone 5s, iOS 10.3.2).

I receive notification messages from GCM when the app is open but i don't receive any notifications from APN when the app is closed.

I'm trying to debug this for few days now but cannot figure out where is the problem... Looks like Firebase is not sending the message to APN but my .p12 key is correctly setup...

1. Does the plugin takes care to register the device with APN?
2. Is there an easy way to get the APN Device Token (to send a message directly to APN)
3. Any other idea of how i can debug this?

**Comment by EddyVerbruggen** [comment]
Please share a repo I can clone and run/debug as it can be anything really.

**Comment by KingAndroid** [comment]
Hello @EddyVerbruggen 
Please check this example repository.
Thanks.
https://github.com/KingAndroid/nativescript-plugin-firebase-demo/tree/fcm_ios_background

**Comment by EddyVerbruggen** [comment]
Thanks @KingAndroid, I'll check it out soon!

**Comment by EddyVerbruggen** [comment]
Hey @KingAndroid, have you seen [this comment](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/359#issuecomment-303953577)? It's exactly what may fix the problem for you as you also run `init` before the app is launched. It seems to work nicely for the others in that thread.

**Comment by mfradcourt** [comment]
@EddyVerbruggen I was also running the `init` before the launch of the app... Executing the `init` after the loading of the app is working for me.

**Comment by KingAndroid** [comment]
Still same issue.
I moved init method to first view pageloaded method.
But I still did not get notification on background.
My test case is as follow.
1. remove app fully from iDevice or Simulator
2. launch app
3. test in forground -> works well
4. press Home or CMD + L => App will be on background.
5. test again -> not work!

What is still missing?
Thanks.

**Comment by mfradcourt** [comment]
@KingAndroid 
App setup looks good (for the demo project you provided)

I would confirm the following:

Apple setup
- iPhone Developer certificate in the keychain
- Apple Development IOS Push Services certificate in the keychain

Firebase setup
- Create a specific iOS app (with the correct "BundleID" & "App ID Prefix")
- **Setup the APNs Certificates**

**Comment by KingAndroid** [comment]
Hello @mfradcourt 
Thank you for your response.
Because fcm works well on forground, I think bundle id or certification issue can be ignored.
am i right ? or ...

**Comment by KingAndroid** [comment]
One more, do I should test on real device?
I am trying on ios simulator, it works on forground and not on background
Thanks

**Comment by mfradcourt** [comment]
Firebase notifications are different than Apple Notifications.
Firebase is sending a notification to Apple which is then sending it to your device.

You need a real device to test the background notifications (as far as i know) because you need to register the test device in your apple developer account and add it to your apple profile.

**Comment by KingAndroid** [comment]
I've tried as below.
1. all revoke certs and try again
2. test on real device -> got token, works on foreground, but not on background.

Yes, but we can try with iOSEmulatorFlush: true on ios simulator.

**Comment by KingAndroid** [comment]
I've test using native push notification by creating new swift project.
Used same app bundle id, and used same certifications.
All works well perfectly includes background and killed case.

Which case would we try then?
Thanks

**Comment by spstratis** [comment]
I also tried moving the init method so that it was called in one of the starting web views and am still not able to receive notifications while the application is running in the background. 

I'm using NS 3.0.3, iOS 10.3.2  and the 3.11.4 version of the Firebase plugin.

**Comment by KingAndroid** [comment]
I am using NS 3.0.2, ios 10.3.2 and 3.12.0

**Comment by KingAndroid** [comment]
In fact this issues was fixed on this plugin, but after merging, it was removed suddenly.

**Comment by spstratis** [comment]
bah even after updating to 3.12.0 I'm still not getting the notifications while the app is in the background. I guess I could try downgrading NS to 3.0.2 but I feel as though that isn't the problem.

**Comment by spstratis** [comment]
I can now confirm that on ver 3.12.0 the plugin, moving the firebase initialization outside of the app.ts file and into one of my first onloaded events fixed the issue. Notifications are now displaying.

**Comment by sserdyuk** [comment]
I am experiencing the same issue. Tried moving `firebase.init()` to  `application.on(application.launchEvent`, but that doesn't help. I am weary of moving the init further in the app, as I am planning to use firebase to store app state, and I need to be able to load it early on.

**Comment by sserdyuk** [comment]
@EddyVerbruggen To follow up on my previous comment, downgrading to 3.12 helped me, so you may give 4.0.2 a hard look. Also, I'd recommend to change the README, to call firebase.init on `application.launchEvent` event as this corresponds with what Firebase docs are recommending. Cheers and Thank you for a great plugin! 

`Configure a FIRApp shared instance, typically in your application's application:didFinishLaunchingWithOptions: method`

**Comment by sserdyuk** [comment]
@EddyVerbruggen While initing on the launch event works in iOS, it doesn't in Android (token never gets assigned). In my app, I made two branches based on the platform. Again, this is with version 3.12.

I am still having issues with some edge cases. For example, on iOS background notification appears, and I can launch the app from it, but once launched, the app doesn't get the details of the message.

Another strange issue is that on Android, the data part isn't being passed when the app is active. Background messages work fine.

**Comment by briandilley** [comment]
I'm having a similar problem.  Everything works fine for me on both platforms in development.  But on iOS once I've submitted it to the app store and install it via TestFlight I don't receive the notifications (registration works and I get an FCM push token though).

**Comment by sserdyuk** [comment]
@briandilley do you have the correct apn certificate loaded into firebase settings for iOS production?

**Comment by briandilley** [comment]
@sserdyuk /facepalm - that was it :(

**Comment by briandilley** [comment]
Except now it only works on the first launch of the app - and only in the foreground. never in the background.

**Comment by briandilley** [comment]
I wrote some wrapper/helper code to make using `nativescript-plugin-firebase` easier for notifications.  You'll find said code below.  Basically, just call `setupNotificationManager()` in your `main.ts` before starting the application and then whenever you're ready for `firebase.init()` to be called use `NotificationManager.instance.registerForPushNotifications()`.  Then, to listen to notifications use `NotificationManager.instance.notifications()`.

This all works perfectly on Android.  But on iOS there are no notififcations delivered in the foreground or background on subsequent app launches.

firebase.ts
```
import {Subscriber} from "rxjs";
import {TeardownLogic} from "rxjs/Subscription";

export type ObservableProducer<T> = {(subscriber: Subscriber<T>) : TeardownLogic};

let _firebase: any = null;

export function firebaseProducer(): ObservableProducer<any> {
    return (subscriber) => {
        if (!_firebase) {
            _firebase = require("nativescript-plugin-firebase");
        }
        subscriber.next(_firebase);
        subscriber.complete();
    };
}

export function createPushtokenProducer(firebase: any): ObservableProducer<string> {
    return (subscriber) => {
        firebase.getCurrentPushToken().then(
            (token) => {
                subscriber.next(token);
                subscriber.complete();
            },
            (error) => subscriber.error(error));
    }
}

export function createInitializationProducer(firebase: any, handler: {(message: any)}): ObservableProducer<any> {
    return (subscriber) => {
        firebase.init({
                onMessageReceivedCallback: (message) => {
                    console.log(`MESSAGE[`
                        + `message.title:${message.title}, `
                        + `message.body:${message.body}]`);
                    handler(message);
                },

                // handles the tokens
                onPushTokenReceivedCallback: (pushToken) => {
                    console.log(`TOKEN[${pushToken}]`);
                }
            })
            .then(
                (value) => {
                    console.log('firebase.init() success');
                    subscriber.next(value);
                    subscriber.complete();
                },
                (error) => {
                    console.log('firebase.init() failure');
                    subscriber.error(error);
                });
    }
}
```

manager.ts
```
import {Observable} from "rxjs";
import {createInitializationProducer, createPushtokenProducer, firebaseProducer} from "./firebase";

export type NotificationListener = {(notification: Notification) : void};

export class Notification {
    public constructor(
        public title: string,
        public message: string,
        public data: any) {
    }
}

export class NotificationManager {

    private static _instance: NotificationManager = null;

    public static get instance() : NotificationManager {
        if (NotificationManager._instance == null) {
            NotificationManager._instance = new NotificationManager();
        }
        return NotificationManager._instance;
    }

    private listeners: NotificationListener[] = [];
    private _registered: boolean = false;

    private constructor() {

    }

    public get registered(): boolean {
        return this._registered;
    }

    public notifications(): Observable<Notification> {
        return new Observable((sub) => {
            let listener: NotificationListener = (notification) => sub.next(notification);
            this.addNotificationListener(listener);
            return () => this.removeNotificationListener(listener);
        });
    }

    public broadcastNotification(notification: Notification) {
        this.listeners.slice().forEach((l) => l(notification));
    }

    public broadcastMessage(notification: Notification) {
        this.listeners.slice().forEach((l) => l(notification));
    }

    public addNotificationListener(listener: NotificationListener) {
        this.listeners.push(listener);
    }

    public removeNotificationListener(listener: NotificationListener) {
        let index = this.listeners.indexOf(listener);
        if (index != -1) {
            this.listeners.splice(index, 1);
        }
    }

    public getPushToken(): Observable<string> {
        return new Observable(firebaseProducer())
            .flatMap((firebase) => new Observable(createPushtokenProducer(firebase)));
    }

    public registerForPushNotifications(): Observable<string> {
        return new Observable(firebaseProducer())
            .flatMap((firebase) => Observable.if(
                // if
                () => this._registered == true,
                    // then
                    new Observable(createPushtokenProducer(firebase)),
                    // else
                    new Observable(createInitializationProducer(firebase,(message) => {
                        this._registered = true;
                        this.broadcastNotification(new Notification(message.title, message.body, message.data));
                    }))
                    .flatMap(() => new Observable(createPushtokenProducer(firebase)))
                ));
    }

    public getCurrentPushToken(): Observable<string> {
        return new Observable(firebaseProducer())
            .flatMap((firebase) => new Observable(createPushtokenProducer(firebase)));
    }
}
```

autoregister.ts
```
import {NotificationManager} from "./";

export function setupNotificationManager(): void {
    // add your own logic for HAS_STORED_PUSH_TOKEN
    if (HAS_STORED_PUSH_TOKEN == false) {
        console.log("Not autoregistering for push notifications yet, we haven't asked for permission");
        return;
    }

    console.log("Autoregistering for push notifications");
    let notificationManager: NotificationManager = NotificationManager.instance;
    notificationManager.registerForPushNotifications()
        .subscribe(
            (pushToken) => console.log(`push notification registration successful: ${pushToken}`),
            (error) => console.error(error, "error autoregistering push notifications"),
            () => console.log("push notification autoregistration completed"));

}
```

**Comment by briandilley** [comment]
Any update on this one?

**Comment by simonox** [comment]
nativescript-push-plugin worked for me. It gives you a APNS token for iOS devices (not a FCM token) and a FCM token for Android devices on registration. You can convert APNS tokens to FCM tokens (via a REST API) to use FCM as a single remote push provider.

**Comment by sudhanshu-15** [comment]
I am also facing the same issue, background notification on iOS has stopped working. It was working before and my organization has been using push notifications for some time now. I followed the instructions mentioned above and change the init from before app start to after app start. This made Android to stop receiving notifications in foreground. Where as iOS was not able to receive background notification in either case. Any help will be appreciated. I hope we can resolve this issue again.

**Comment by mfradcourt** [comment]
@briandilley Are you sure you use setup the apple certificate to be production? Common error is to configure for development... The notifications will not work with unregistered devices

**Comment by briandilley** [comment]
Its working for me now, did a fresh setup.

**Comment by sundargsv** [comment]
Hi @briandilley, If you could share your Push Notification (Demo app - iOS) It would be very grateful. Request you to help us with by sharing working samples ASAP.

And now I'm confused ? Like should I use  nativescript-plugin-firebase or any other alternatives for iOS push notifications (Background and Foreground).
Thanks in advance.

**Comment by shiamalon** [comment]
I ended up on this thread a lot when I was trying to figure out how to get it working.  IOs background notifications I could only get them working on a real device.

**Comment by EddyVerbruggen** [comment]
@shiamalon Background notifications on iOS sim are not possible. Not related to this plugin nor Firebase.

**Comment by shiamalon** [comment]
@EddyVerbruggen I never saw that info very clear anywhere that's why I'm saying it. Maybe it is. It's just my 2 cents noob.

Btw thanks for your plugin!

**Comment by giordanocardillo** [comment]
Here I have iOS 11.2 on an iPhone 5S and I cannot get the backgrund notifications to work. Plugin version is 5.0.2... Please @EddyVerbruggen gimme some help! I've configured the FCM with APNs Auth Key (as suggested by Google) and not with the two certs (I can't get the p12 for the development one because it hasn't a key). The plugin `firebase.init` method is being called in the onpageloaded method of the first application view... What can I do to get it working?

**Comment by giordanocardillo** [comment]
Ok, solved it, thanks to this https://discourse.nativescript.org/t/how-to-implement-push-notification-on-nativescript-angular-2/173/23

I just had to put a setTimeout around the firebase.init method. I also call it inside the main app bootstrap file.

**Comment by Frederiks96** [comment]
I had this problem as well, checked the provisioning profile validity, added the required background modes in the `Info.plist`, added entitlements to the `AppName.entitlements` and placed it in the right folder. My setup is using NativeScript-Vue with Typescript and I have come to the conclusion that the Typescript import `import Firebase from "nativescript-plugin-firebase";` doesn't seem to work for background notifications? Changing the import to `const Firebase = require("nativescript-plugin-firebase");` did the trick. Just wanted to add this in case other users have similar problems..

**Comment by EddyVerbruggen** [comment]
Thanks for sharing that, @Frederiks96 - I hope the docs in this repo make this clear as well (user require instead of import because the latter gets removed bt the TS transpiler if the import is not used). Cheers!

**Comment by Frederiks96** [comment]
Thanks for the reply @EddyVerbruggen, I must have missed that then.. My mistake.. But could it be that the import is case sensitive? I imported `Firebase` (with a capital F) instead of `firebase` - I am new to Typescript/JS (coming from native iOS), so I am figuring it out as I go..

**Comment by EddyVerbruggen** [comment]
No worries mate. The import depends a bit on what parts of the plugin you want to use. The demo apps in this repo show several alternatives. But as you found out, the import in the entry component (main.ts / app.ts) must be `require` unless you also use the import on that page.
